sudo: required

language: c

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - xorg-server-xwayland
    - asciidoc
    - pcre
    - json-c
    - pixman
    - wayland
    - libxkbcommon
    - libinput
    - libx11
    - libxcb
    - xcb-util-image
    - libgl
    - mesa
    - pango
    - cairo
    - gdk-pixbuf2
  script:
    - "bash .ci/build.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
